/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JButton;

/**
 *
 * @author Penguin
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnAsisten = new javax.swing.JButton();
        BtnMahasiswa = new javax.swing.JButton();
        BtnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menu Utama");

        BtnAsisten.setText("Asisten");

        BtnMahasiswa.setText("Mahasiswa");

        BtnEdit.setText("Edit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnAsisten)
                        .addGap(40, 40, 40)
                        .addComponent(BtnMahasiswa)
                        .addGap(40, 40, 40)
                        .addComponent(BtnEdit)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAsisten)
                    .addComponent(BtnMahasiswa)
                    .addComponent(BtnEdit))
                .addContainerGap(182, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public JButton getBtnAsisten() {
        return BtnAsisten;
    }

    public JButton getBtnEdit() {
        return BtnEdit;
    }

    public JButton getBtnMahasiswa() {
        return BtnMahasiswa;
    }



   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAsisten;
    private javax.swing.JButton BtnEdit;
    private javax.swing.JButton BtnMahasiswa;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
