/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JButton;

/**
 *
 * @author Penguin
 */
public class MenuMahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form MenuMahasiswa
     */
    public MenuMahasiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnaddMhs = new javax.swing.JButton();
        BtnCariMhs = new javax.swing.JButton();
        BtnHapusMhs = new javax.swing.JButton();
        BtnHalamanUtama = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menu Mahasiswa");

        BtnaddMhs.setText("Tambah Mahasiswa");

        BtnCariMhs.setText("Login Mahasiswa");
        BtnCariMhs.setToolTipText("");

        BtnHapusMhs.setText("Hapus Mahasiswa");

        BtnHalamanUtama.setText("Ke menu halaman utama");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnaddMhs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnHapusMhs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnCariMhs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(156, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnHalamanUtama)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(BtnaddMhs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnCariMhs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnHapusMhs)
                .addGap(18, 18, 18)
                .addComponent(BtnHalamanUtama)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCariMhs;
    private javax.swing.JButton BtnHalamanUtama;
    private javax.swing.JButton BtnHapusMhs;
    private javax.swing.JButton BtnaddMhs;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

        public JButton getBtnHalamanUtama() {
           return BtnHalamanUtama;
       }
       
       public JButton getaddMhs() {
           return BtnaddMhs;
       }
       
       public JButton getBtnCariMhs() {
           return BtnCariMhs;
       }
       
       public JButton getBtnHapusMhs() {
           return BtnHapusMhs;
       }

    public JButton getBtnaddMhs() {
        return BtnaddMhs;
    }
       
       
    
}
