/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import javax.swing.JButton;

/**
 *
 * @author HP1000
 */
public class SubMenuAsisten extends javax.swing.JFrame {

    /**
     * Creates new form SubMenuAsisten
     */
    public SubMenuAsisten() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnAddAsisten = new javax.swing.JButton();
        BtnCariAsisten = new javax.swing.JButton();
        BtnHapusAsisten = new javax.swing.JButton();
        BtnBackMenuAs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sub Menu Asisten");

        BtnAddAsisten.setText("Tambah Data Asisten");

        BtnCariAsisten.setText("Cari Data Asisten");

        BtnHapusAsisten.setText("Hapus Data Asisten");

        BtnBackMenuAs.setText("Kembali ke Menu Asisten");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnAddAsisten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnCariAsisten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnHapusAsisten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(121, 121, 121))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnBackMenuAs)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addComponent(BtnAddAsisten)
                .addGap(18, 18, 18)
                .addComponent(BtnCariAsisten)
                .addGap(18, 18, 18)
                .addComponent(BtnHapusAsisten)
                .addGap(61, 61, 61)
                .addComponent(BtnBackMenuAs)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public JButton getBtnAddAsisten() {
        return BtnAddAsisten;
    }

    public JButton getBtnBackMenuAs() {
        return BtnBackMenuAs;
    }

    public JButton getBtnCariAsisten() {
        return BtnCariAsisten;
    }

    public JButton getBtnHapusAsisten() {
        return BtnHapusAsisten;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddAsisten;
    private javax.swing.JButton BtnBackMenuAs;
    private javax.swing.JButton BtnCariAsisten;
    private javax.swing.JButton BtnHapusAsisten;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
