/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JButton;

/**
 *
 * @author Penguin
 */
public class SubMenuMahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form SubMenuMahasiswa
     */
    public SubMenuMahasiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnTambahKeTugasBesar = new javax.swing.JButton();
        BtnTambahDokumentasiKeTugasBesar = new javax.swing.JButton();
        BtnHapusDokumentasiTugasBesar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BtnHalamanUtama = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnTambahKeTugasBesar.setText("Tambah Ke tugas besar");

        BtnTambahDokumentasiKeTugasBesar.setText("Tambah Dokumentasi ke tugas besar");
        BtnTambahDokumentasiKeTugasBesar.setToolTipText("");

        BtnHapusDokumentasiTugasBesar.setText("Hapus dokumentasi tugas besar");

        jLabel1.setText("Sub Menu Mahasiswa");

        BtnHalamanUtama.setText("Kembali Ke Menu Utama");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnTambahKeTugasBesar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnHapusDokumentasiTugasBesar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnTambahDokumentasiKeTugasBesar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnHalamanUtama)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(BtnTambahKeTugasBesar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnTambahDokumentasiKeTugasBesar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnHapusDokumentasiTugasBesar)
                .addGap(44, 44, 44)
                .addComponent(BtnHalamanUtama)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnHalamanUtama;
    private javax.swing.JButton BtnHapusDokumentasiTugasBesar;
    private javax.swing.JButton BtnTambahDokumentasiKeTugasBesar;
    private javax.swing.JButton BtnTambahKeTugasBesar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    public JButton getBtnHalamanUtama() {
        return BtnHalamanUtama;
    }

    public JButton getBtnTambahDokumentasiKeTugasBesar() {
        return BtnTambahDokumentasiKeTugasBesar;
    }

    public JButton getBtnHapusDokumentasiTugasBesar() {
        return BtnHapusDokumentasiTugasBesar;
    }

    public JButton getBtnTambahKeTugasBesar() {
        return BtnTambahKeTugasBesar;
    }


}
