/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Component;
import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Penguin
 */
public class TambahAsisten extends javax.swing.JFrame {

    /**
     * Creates new form Asisten
     */
    public TambahAsisten() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Masukkan Data Asisten");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextNamaAsisten = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TextAlamatAsisten = new javax.swing.JTextField();
        TextNoHPAsisten = new javax.swing.JTextField();
        RadioBtnCowo = new javax.swing.JRadioButton();
        TextIDAsisten = new javax.swing.JTextField();
        RadioBtnCewe = new javax.swing.JRadioButton();
        BtnSimpanAsisten = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BtnMainMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 300));

        jLabel4.setText("Nomor Handphone");

        jLabel3.setText("Alamat");

        jLabel2.setText("Nama");

        TextNamaAsisten.setText("Nama Asisten");
        TextNamaAsisten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNamaAsistenActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Masukan Data Asisten");

        TextAlamatAsisten.setText("Alamat Asisten");

        TextNoHPAsisten.setText("Nomor Handphone Asisten");

        buttonGroup1.add(RadioBtnCowo);
        RadioBtnCowo.setText("Laki-Laki");
        RadioBtnCowo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBtnCowoActionPerformed(evt);
            }
        });

        TextIDAsisten.setText("ID Asisten");
        TextIDAsisten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextIDAsistenActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioBtnCewe);
        RadioBtnCewe.setText("Perempuan");
        RadioBtnCewe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBtnCeweActionPerformed(evt);
            }
        });

        BtnSimpanAsisten.setText("Simpan");

        jLabel6.setText("NIM");

        jLabel7.setText("Menu Utama>Asisten>Tambah Asisten");

        jLabel5.setText("Jenis Kelamin");

        BtnMainMenu.setText("Kembali ke Menu Utama");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(BtnSimpanAsisten)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(BtnMainMenu))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextIDAsisten)
                                    .addComponent(TextNamaAsisten)
                                    .addComponent(TextAlamatAsisten)
                                    .addComponent(RadioBtnCewe)
                                    .addComponent(RadioBtnCowo)
                                    .addComponent(TextNoHPAsisten, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextNamaAsisten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextAlamatAsisten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TextNoHPAsisten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RadioBtnCowo)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioBtnCewe)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextIDAsisten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSimpanAsisten)
                    .addComponent(BtnMainMenu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnSimpanAsisten() {
        return BtnSimpanAsisten;
    }

    public JRadioButton getRadioBtnCewe() {
        return RadioBtnCewe;
    }

    public JRadioButton getRadioBtnCowo() {
        return RadioBtnCowo;
    }

    public JTextField getTextAlamatAsisten() {
        return TextAlamatAsisten;
    }

    public JTextField getTextIDAsisten() {
        return TextIDAsisten;
    }

    public JTextField getTextNamaAsisten() {
        return TextNamaAsisten;
    }

    public JTextField getTextNoHPAsisten() {
        return TextNoHPAsisten;
    }

    public JButton getBtnMainMenu() {
        return BtnMainMenu;
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }
    
   
    private void RadioBtnCowoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBtnCowoActionPerformed
        // TODO add your handling code here:
        String jk="";
        if (this.RadioBtnCowo.isSelected()){
            jk = RadioBtnCowo.getText();
        }
    }//GEN-LAST:event_RadioBtnCowoActionPerformed

    private void TextNamaAsistenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNamaAsistenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNamaAsistenActionPerformed

    private void TextIDAsistenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextIDAsistenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextIDAsistenActionPerformed

    private void RadioBtnCeweActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBtnCeweActionPerformed
        // TODO add your handling code here:
        String jk="";
        if (this.RadioBtnCewe.isSelected()){
            jk = RadioBtnCewe.getText();
        }
    }//GEN-LAST:event_RadioBtnCeweActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TambahAsisten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TambahAsisten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TambahAsisten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TambahAsisten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TambahAsisten().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnMainMenu;
    private javax.swing.JButton BtnSimpanAsisten;
    private javax.swing.JRadioButton RadioBtnCewe;
    private javax.swing.JRadioButton RadioBtnCowo;
    private javax.swing.JTextField TextAlamatAsisten;
    private javax.swing.JTextField TextIDAsisten;
    private javax.swing.JTextField TextNamaAsisten;
    private javax.swing.JTextField TextNoHPAsisten;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
                   


    public void addListener(ActionListener e){
        BtnSimpanAsisten.addActionListener(e);
    }

    public void showMessage(Component  c, String s){
        JOptionPane.showMessageDialog(c, s);
    }
}
